databaseType = "PostgreSql"
name = "V9__InitTables"
id = "2c311951-8cf2-4668-9d7d-608c1885207f"

[flywayDesktop]
developmentEnvironment = "development"
shadowEnvironment = "shadow"
schemaModel = "schema-model"

[flyway]

[redgateCompare]
filterFile = "filter.rgf"